import json

# List of 50 test commands
test_commands = [
    {"id":"test-001","command":"ls","category":"Navigation","description":"Lists files and directories in current location.","example_output":"file1.txt file2.txt","man_reference":"https://man7.org/linux/man-pages/man1/ls.1.html"},
    {"id":"test-002","command":"pwd","category":"Navigation","description":"Prints current working directory.","example_output":"/home/user","man_reference":"https://man7.org/linux/man-pages/man1/pwd.1.html"},
    {"id":"test-003","command":"cd /tmp","category":"Navigation","description":"Changes directory to /tmp.","example_output":"[No output, changes directory]","man_reference":"https://man7.org/linux/man-pages/man1/cd.1.html"},
    {"id":"test-004","command":"mkdir testdir","category":"File Management","description":"Creates a new directory named testdir.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/mkdir.1.html"},
    {"id":"test-005","command":"rm -rf testdir","category":"File Management","description":"Deletes the directory testdir and its contents.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/rm.1.html"},
    {"id":"test-006","command":"touch testfile.txt","category":"File Management","description":"Creates an empty file named testfile.txt.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/touch.1.html"},
    {"id":"test-007","command":"cp testfile.txt backup.txt","category":"File Management","description":"Copies testfile.txt to backup.txt.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/cp.1.html"},
    {"id":"test-008","command":"mv backup.txt backup2.txt","category":"File Management","description":"Renames backup.txt to backup2.txt.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/mv.1.html"},
    {"id":"test-009","command":"cat testfile.txt","category":"Viewing","description":"Displays the contents of testfile.txt.","example_output":"[File content]","man_reference":"https://man7.org/linux/man-pages/man1/cat.1.html"},
    {"id":"test-010","command":"less testfile.txt","category":"Viewing","description":"Views testfile.txt with pagination.","example_output":"[Interactive display]","man_reference":"https://man7.org/linux/man-pages/man1/less.1.html"},
    {"id":"test-011","command":"head -n 3 testfile.txt","category":"Viewing","description":"Displays first 3 lines of testfile.txt.","example_output":"[First 3 lines]","man_reference":"https://man7.org/linux/man-pages/man1/head.1.html"},
    {"id":"test-012","command":"tail -n 3 testfile.txt","category":"Viewing","description":"Displays last 3 lines of testfile.txt.","example_output":"[Last 3 lines]","man_reference":"https://man7.org/linux/man-pages/man1/tail.1.html"},
    {"id":"test-013","command":"uname -a","category":"System Info","description":"Displays system information.","example_output":"Linux host 5.15.0-73-generic #80-Ubuntu SMP","man_reference":"https://man7.org/linux/man-pages/man1/uname.1.html"},
    {"id":"test-014","command":"top -n 1","category":"System Info","description":"Shows snapshot of running processes.","example_output":"[Process snapshot]","man_reference":"https://man7.org/linux/man-pages/man1/top.1.html"},
    {"id":"test-015","command":"df -h","category":"System Info","description":"Shows disk usage in human-readable format.","example_output":"Filesystem Size Used Avail Use% Mounted on\n/dev/sda1 100G 50G 50G 50% /","man_reference":"https://man7.org/linux/man-pages/man1/df.1.html"},
    {"id":"test-016","command":"free -m","category":"System Info","description":"Displays memory usage in MB.","example_output":"total used free shared buff/cache available\nMem: 8192 4096 2048 512 2048 4096","man_reference":"https://man7.org/linux/man-pages/man1/free.1.html"},
    {"id":"test-017","command":"chmod 755 script.sh","category":"Permissions","description":"Sets script.sh to executable.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/chmod.1.html"},
    {"id":"test-018","command":"chown user:user testfile.txt","category":"Permissions","description":"Changes ownership of testfile.txt to user.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/chown.1.html"},
    {"id":"test-019","command":"apt update","category":"Package Management","description":"Updates package lists on Debian systems.","example_output":"Reading package lists... Done","man_reference":"https://man7.org/linux/man-pages/man8/apt.8.html"},
    {"id":"test-020","command":"apt install vim","category":"Package Management","description":"Installs Vim editor on Debian systems.","example_output":"Setting up vim (8.0)...","man_reference":"https://man7.org/linux/man-pages/man8/apt.8.html"},
    {"id":"test-021","command":"yum install wget","category":"Package Management","description":"Installs wget on CentOS/RHEL systems.","example_output":"Installing: wget-1.20.3-1.el8.x86_64","man_reference":"https://man7.org/linux/man-pages/man8/yum.8.html"},
    {"id":"test-022","command":"dnf install curl","category":"Package Management","description":"Installs curl on Fedora systems.","example_output":"Installing: curl-7.76.1-1.fc34.x86_64","man_reference":"https://man7.org/linux/man-pages/man8/dnf.8.html"},
    {"id":"test-023","command":"ping -c 2 8.8.8.8","category":"Networking","description":"Sends 2 ICMP requests to 8.8.8.8.","example_output":"2 packets transmitted, 2 received, 0% packet loss","man_reference":"https://man7.org/linux/man-pages/man8/ping.8.html"},
    {"id":"test-024","command":"ifconfig -a","category":"Networking","description":"Displays all network interfaces.","example_output":"eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500\ninet 192.168.1.100","man_reference":"https://man7.org/linux/man-pages/man8/ifconfig.8.html"},
    {"id":"test-025","command":"netstat -tulpn","category":"Networking","description":"Shows all listening ports.","example_output":"tcp 0 0 0.0.0.0:22 0.0.0.0:* LISTEN","man_reference":"https://man7.org/linux/man-pages/man8/netstat.8.html"},
    {"id":"test-026","command":"whoami","category":"User Management","description":"Displays current user name.","example_output":"user","man_reference":"https://man7.org/linux/man-pages/man1/whoami.1.html"},
    {"id":"test-027","command":"id","category":"User Management","description":"Shows user and group IDs.","example_output":"uid=1000(user) gid=1000(user) groups=1000(user)","man_reference":"https://man7.org/linux/man-pages/man1/id.1.html"},
    {"id":"test-028","command":"adduser testuser","category":"User Management","description":"Adds a new user testuser.","example_output":"Adding user `testuser' ...","man_reference":"https://man7.org/linux/man-pages/man8/adduser.8.html"},
    {"id":"test-029","command":"passwd testuser","category":"User Management","description":"Changes password for testuser.","example_output":"Enter new UNIX password:","man_reference":"https://man7.org/linux/man-pages/man1/passwd.1.html"},
    {"id":"test-030","command":"userdel testuser","category":"User Management","description":"Deletes user testuser.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man8/userdel.8.html"},
    {"id":"test-031","command":"ps aux","category":"Process","description":"Displays all running processes.","example_output":"user 1234 0.1 0.2 123456 7890 ? S 11:02 0:00 /usr/bin/python3","man_reference":"https://man7.org/linux/man-pages/man1/ps.1.html"},
    {"id":"test-032","command":"kill -9 1234","category":"Process","description":"Forcefully kills process with PID 1234.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/kill.1.html"},
    {"id":"test-033","command":"htop","category":"Process","description":"Interactive process viewer.","example_output":"[Interactive monitor]","man_reference":"https://man7.org/linux/man-pages/man1/htop.1.html"},
    {"id":"test-034","command":"vim testfile.txt","category":"Editor","description":"Opens testfile.txt in Vim editor.","example_output":"[Interactive editor interface]","man_reference":"https://man7.org/linux/man-pages/man1/vim.1.html"},
    {"id":"test-035","command":"nano testfile.txt","category":"Editor","description":"Opens testfile.txt in Nano editor.","example_output":"[Interactive editor interface]","man_reference":"https://man7.org/linux/man-pages/man1/nano.1.html"},
    {"id":"test-036","command":"cd ..","category":"Navigation","description":"Moves up one directory level.","example_output":"[No output, changes directory]","man_reference":"https://man7.org/linux/man-pages/man1/cd.1.html"},
    {"id":"test-037","command":"ls -lh","category":"Navigation","description":"Lists files with human-readable sizes.","example_output":"-rw-r--r-- 1 user user 1.2M May 21 2025 file.txt","man_reference":"https://man7.org/linux/man-pages/man1/ls.1.html"},
    {"id":"test-038","command":"cp -r dir1 dir2","category":"File Management","description":"Recursively copies dir1 to dir2.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/cp.1.html"},
    {"id":"test-039","command":"mv -i file.txt /tmp","category":"File Management","description":"Moves file.txt to /tmp with confirmation if overwriting.","example_output":"mv: overwrite '/tmp/file.txt'? y","man_reference":"https://man7.org/linux/man-pages/man1/mv.1.html"},
    {"id":"test-040","command":"rm -i file.txt","category":"File Management","description":"Deletes file.txt interactively.","example_output":"rm: remove regular file 'file.txt'? y","man_reference":"https://man7.org/linux/man-pages/man1/rm.1.html"},
    {"id":"test-041","command":"cat -n testfile.txt","category":"Viewing","description":"Displays testfile.txt with line numbers.","example_output":"1 First line\n2 Second line","man_reference":"https://man7.org/linux/man-pages/man1/cat.1.html"},
    {"id":"test-042","command":"less +G testfile.txt","category":"Viewing","description":"Opens testfile.txt in less from the end.","example_output":"[Interactive display from end]","man_reference":"https://man7.org/linux/man-pages/man1/less.1.html"},
    {"id":"test-043","command":"head -c 50 testfile.txt","category":"Viewing","description":"Displays first 50 bytes of testfile.txt.","example_output":"[First 50 bytes]","man_reference":"https://man7.org/linux/man-pages/man1/head.1.html"},
    {"id":"test-044","command":"tail -n +2 testfile.txt","category":"Viewing","description":"Displays testfile.txt starting from line 2.","example_output":"[All lines except first]","man_reference":"https://man7.org/linux/man-pages/man1/tail.1.html"},
    {"id":"test-045","command":"uname -r","category":"System Info","description":"Displays kernel release version.","example_output":"5.15.0-73-generic","man_reference":"https://man7.org/linux/man-pages/man1/uname.1.html"},
    {"id":"test-046","command":"df /","category":"System Info","description":"Shows disk usage for root filesystem.","example_output":"Filesystem 1K-blocks Used Available Use% Mounted on\n/dev/sda1 104857600 52428800 52428800 50% /","man_reference":"https://man7.org/linux/man-pages/man1/df.1.html"},
    {"id":"test-047","command":"free -h","category":"System Info","description":"Displays memory usage in human-readable format.","example_output":"total used free shared buff/cache available\nMem: 8.0G 4.0G 2.0G 512M 2.0G 4.0G","man_reference":"https://man7.org/linux/man-pages/man1/free.1.html"},
    {"id":"test-048","command":"chmod 644 testfile.txt","category":"Permissions","description":"Sets testfile.txt to read/write owner, read-only others.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/chmod.1.html"},
    {"id":"test-049","command":"chown -R user:user testdir","category":"Permissions","description":"Recursively changes ownership of testdir.","example_output":"[No output if successful]","man_reference":"https://man7.org/linux/man-pages/man1/chown.1.html"},
    {"id":"test-050","command":"apt autoremove","category":"Package Management","description":"Removes unused dependencies on Debian systems.","example_output":"Reading package lists... Done\n0 to remove","man_reference":"https://man7.org/linux/man-pages/man8/apt.8.html"}
]

# Write to a JSON file
with open("test_commands.json", "w") as f:
    for cmd in test_commands:
        f.write(json.dumps(cmd) + "\n")

print("Test dataset with 50 commands has been created as 'test_commands.json'.")
